
import { useEffect, useMemo, useRef, useState } from 'react';
import { Download, Edit3, Eye, File, FileImage, FileSpreadsheet, FileText, Folder, MoreVertical, Plus, Trash2, Upload, X } from 'lucide-react';
import { deleteJson, getJson, postJson, putJson, uploadForm } from '../lib/api';
type FolderRow={name:string;count:number};type Doc={id:number;name:string;originalFileName:string;category:string;entityType:string;entityId:number;project?:string;author?:string;uploadedAt:string;fileSize:number;mimeType:string;downloadUrl:string};type Overview={folders:FolderRow[];documents:Doc[]};type Project={id:number;name:string};
const size=(n:number)=>n>=1048576?`${(n/1048576).toFixed(1)} MB`:n>=1024?`${Math.round(n/1024)} KB`:`${n} B`;
const icon=(m:string)=>m.includes('sheet')||m.includes('excel')?<FileSpreadsheet/>:m.startsWith('image/')?<FileImage/>:m.includes('pdf')||m.includes('word')?<FileText/>:<File/>;
export function DocumentsPage(){
 const [data,setData]=useState<Overview|null>(null),[projects,setProjects]=useState<Project[]>([]),[folder,setFolder]=useState('ALL'),[openFolder,setOpenFolder]=useState(false),[newFolder,setNewFolder]=useState(''),[error,setError]=useState('');const fileRef=useRef<HTMLInputElement|null>(null);
 const load=async()=>{const [d,p]=await Promise.all([getJson<Overview>('/documents/overview'),getJson<Project[]>('/projects')]);setData(d);setProjects(p)};useEffect(()=>{load().catch(e=>setError(String(e)))},[]);
 const docs=useMemo(()=>data?.documents.filter(d=>folder==='ALL'||d.category===folder)||[],[data,folder]);
 const upload=async(e:React.ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(!f)return;const fd=new FormData();fd.append('file',f);fd.append('category',folder==='ALL'?'GENERAL':folder);fd.append('orgUnitId','1');fd.append('uploadedBy','1');fd.append('entityType','PROJECT');fd.append('entityId',projects[0]?.id?String(projects[0].id):'0');try{await uploadForm('/documents/upload',fd);await load()}catch(e){setError(String(e))}finally{e.target.value=''}};

 const editDoc=async(d:Doc)=>{const name=prompt('Document name',d.name);if(name===null)return;const category=prompt('Folder / category',d.category);if(category===null)return;try{await putJson(`/documents/${d.id}`,{...d,name,category,status:'ACTIVE'});await load()}catch(e){setError(String(e))}};
 const deleteDoc=async(d:Doc)=>{if(!confirm(`Delete document “${d.originalFileName||d.name}”?`))return;try{await deleteJson(`/documents/${d.id}`);await load()}catch(e){setError(String(e))}};

 const createFolder=async(e:React.FormEvent)=>{e.preventDefault();try{await postJson('/documents/folders',{name:newFolder});setNewFolder('');setOpenFolder(false);await load()}catch(e){setError(String(e))}};
 if(!data)return <div className="loading">{error||'Loading documents...'}</div>;
 return <><div className="page-title"><div><h1>Document Management</h1><p>Manage project documents, contracts, deliverables and reports</p></div><div className="project-actions"><input ref={fileRef} type="file" hidden onChange={upload}/><button className="secondary" onClick={()=>fileRef.current?.click()}><Upload size={16}/> Upload Document</button><button className="budget-primary" onClick={()=>setOpenFolder(true)}><Plus size={16}/> New Folder</button></div></div>{error&&<div className="budget-error">{error}</div>}
 <section className="documents-panel"><h3>Folders</h3><div className="folders-grid"><button className={folder==='ALL'?'folder-card active':'folder-card'} onClick={()=>setFolder('ALL')}><Folder/><div><b>All Documents</b><span>{data.documents.length} files</span></div></button>{data.folders.map(f=><button key={f.name} className={folder===f.name?'folder-card active':'folder-card'} onClick={()=>setFolder(f.name)}><Folder/><div><b>{f.name}</b><span>{f.count} files</span></div></button>)}</div></section>
 <section className="documents-panel"><div className="documents-head"><h3>Recent Documents</h3><span>{docs.length} files</span></div><div className="module-table-wrap"><table className="module-table documents-table"><thead><tr><th>Document</th><th>Folder / Entity</th><th>Author</th><th>Last Modified</th><th>Size</th><th>Actions</th></tr></thead><tbody>{docs.map(d=><tr key={d.id}><td><div className="doc-name">{icon(d.mimeType)}<b>{d.originalFileName||d.name}</b></div></td><td>{d.category}<small>{d.project||`${d.entityType} #${d.entityId}`}</small></td><td>{d.author||'System'}</td><td>{new Date(d.uploadedAt).toLocaleDateString()}</td><td>{size(d.fileSize)}</td><td><div className="doc-actions"><a href={d.downloadUrl} target="_blank"><Eye/></a><a href={d.downloadUrl} download><Download/></a><button onClick={()=>editDoc(d)}><Edit3/></button><button className="danger" onClick={()=>deleteDoc(d)}><Trash2/></button></div></td></tr>)}</tbody></table></div></section>
 {openFolder&&<div className="budget-modal-backdrop" onMouseDown={()=>setOpenFolder(false)}><div className="budget-modal small-modal" onMouseDown={e=>e.stopPropagation()}><div className="budget-modal-head"><div><h3>New Folder</h3><p>Create a document category/folder.</p></div><button onClick={()=>setOpenFolder(false)}><X/></button></div><form onSubmit={createFolder}><label>Folder name<input required value={newFolder} onChange={e=>setNewFolder(e.target.value)} placeholder="Project Charters"/></label><div className="budget-modal-actions"><button type="button" className="secondary" onClick={()=>setOpenFolder(false)}>Cancel</button><button className="budget-primary">Create Folder</button></div></form></div></div>}
 </>;
}
