using MAIPT.PM.Api.Data;
using MAIPT.PM.Api.Models;
using Microsoft.EntityFrameworkCore;
namespace MAIPT.PM.Api.Endpoints;
public static class SettingsEndpoints {
 static bool CanManage(HttpContext h)=>AuthService.IsManagerRole(Convert.ToString(h.Items["AuthUserRole"]));
 public static void MapSettingsEndpoints(this WebApplication app) {
  app.MapGet("/api/settings/portfolios",async(AppDbContext db)=>Results.Ok(await db.Portfolios.AsNoTracking().Include(x=>x.OrgUnit).Include(x=>x.Owner).OrderBy(x=>x.Name).Select(x=>new{x.Id,x.OrgUnitId,x.Code,x.Name,x.Description,x.OwnerId,x.Status,OrgUnit=x.OrgUnit!=null?x.OrgUnit.Name:null,Owner=x.Owner!=null?x.Owner.Name:null,ProjectCount=db.Projects.Count(p=>p.PortfolioId==x.Id)}).ToListAsync()));
  app.MapPost("/api/settings/portfolios",async(Portfolio x,HttpContext h,AppDbContext db)=>{if(!CanManage(h))return Results.Forbid();x.Code=x.Code.Trim().ToUpperInvariant();if(await db.Portfolios.AnyAsync(a=>a.Code==x.Code))return Results.BadRequest("Portfolio code already exists.");db.Portfolios.Add(x);await db.SaveChangesAsync();return Results.Ok(x);});
  app.MapPut("/api/settings/portfolios/{id:long}",async(long id,Portfolio x,HttpContext h,AppDbContext db)=>{if(!CanManage(h))return Results.Forbid();var r=await db.Portfolios.FindAsync(id);if(r==null)return Results.NotFound();r.OrgUnitId=x.OrgUnitId;r.Code=x.Code.Trim().ToUpperInvariant();r.Name=x.Name;r.Description=x.Description;r.OwnerId=x.OwnerId;r.Status=x.Status;await db.SaveChangesAsync();return Results.Ok(r);});
  app.MapDelete("/api/settings/portfolios/{id:long}",async(long id,HttpContext h,AppDbContext db)=>{if(!CanManage(h))return Results.Forbid();var r=await db.Portfolios.FindAsync(id);if(r==null)return Results.NotFound();var n=await db.Projects.CountAsync(x=>x.PortfolioId==id);if(n>0)return Results.BadRequest($"Cannot delete: {n} project(s) use this portfolio. Set INACTIVE instead.");db.Portfolios.Remove(r);await db.SaveChangesAsync();return Results.NoContent();});

  app.MapGet("/api/settings/org-units",async(AppDbContext db)=>Results.Ok(await db.OrgUnits.AsNoTracking().OrderBy(x=>x.Name).Select(x=>new{x.Id,x.Code,x.Name,x.Status,UserCount=db.Users.Count(u=>u.OrgUnitId==x.Id),PortfolioCount=db.Portfolios.Count(p=>p.OrgUnitId==x.Id),ProjectCount=db.Projects.Count(p=>p.OrgUnitId==x.Id)}).ToListAsync()));
  app.MapPost("/api/settings/org-units",async(OrgUnit x,HttpContext h,AppDbContext db)=>{if(!CanManage(h))return Results.Forbid();x.Code=x.Code.Trim().ToUpperInvariant();if(await db.OrgUnits.AnyAsync(a=>a.Code==x.Code))return Results.BadRequest("Business Unit code already exists.");db.OrgUnits.Add(x);await db.SaveChangesAsync();return Results.Ok(x);});
  app.MapPut("/api/settings/org-units/{id:long}",async(long id,OrgUnit x,HttpContext h,AppDbContext db)=>{if(!CanManage(h))return Results.Forbid();var r=await db.OrgUnits.FindAsync(id);if(r==null)return Results.NotFound();r.Code=x.Code.Trim().ToUpperInvariant();r.Name=x.Name;r.Status=x.Status;await db.SaveChangesAsync();return Results.Ok(r);});
  app.MapDelete("/api/settings/org-units/{id:long}",async(long id,HttpContext h,AppDbContext db)=>{if(!CanManage(h))return Results.Forbid();var r=await db.OrgUnits.FindAsync(id);if(r==null)return Results.NotFound();var n=await db.Users.CountAsync(x=>x.OrgUnitId==id)+await db.Portfolios.CountAsync(x=>x.OrgUnitId==id)+await db.Projects.CountAsync(x=>x.OrgUnitId==id);if(n>0)return Results.BadRequest("Cannot delete: this Business Unit is in use. Set INACTIVE instead.");db.OrgUnits.Remove(r);await db.SaveChangesAsync();return Results.NoContent();});

  app.MapGet("/api/settings/team-members",async(AppDbContext db)=>Results.Ok(await db.Users.AsNoTracking().Include(x=>x.OrgUnit).OrderBy(x=>x.Name).Select(x=>new{x.Id,x.OrgUnitId,x.Name,x.Email,x.JobTitle,x.Department,x.Role,x.Status,OrgUnit=x.OrgUnit!=null?x.OrgUnit.Name:null,ProjectCount=db.ProjectMembers.Count(p=>p.UserId==x.Id)}).ToListAsync()));
  app.MapPost("/api/settings/team-members",async(AppUser x,HttpContext h,AppDbContext db)=>{if(!CanManage(h))return Results.Forbid();x.Email=x.Email.Trim().ToLowerInvariant();if(await db.Users.AnyAsync(a=>a.Email==x.Email))return Results.BadRequest("Email already exists.");db.Users.Add(x);await db.SaveChangesAsync();return Results.Ok(x);});
  app.MapPut("/api/settings/team-members/{id:long}",async(long id,AppUser x,HttpContext h,AppDbContext db)=>{if(!CanManage(h))return Results.Forbid();var r=await db.Users.FindAsync(id);if(r==null)return Results.NotFound();r.OrgUnitId=x.OrgUnitId;r.Name=x.Name;r.Email=x.Email.Trim().ToLowerInvariant();r.JobTitle=x.JobTitle;r.Department=x.Department;r.Role=x.Role;r.Status=x.Status;await db.SaveChangesAsync();return Results.Ok(r);});
  app.MapGet("/api/settings/options",async(AppDbContext db)=>Results.Ok(new{orgUnits=await db.OrgUnits.AsNoTracking().OrderBy(x=>x.Name).Select(x=>new{x.Id,x.Code,x.Name,x.Status}).ToListAsync(),users=await db.Users.AsNoTracking().OrderBy(x=>x.Name).Select(x=>new{x.Id,x.Name,x.Email,x.Status}).ToListAsync()}));
 }
}
