namespace MAIPT.PM.Api.Models;
public class PersonalFcCategory { public long Id {get;set;} public long? OwnerUserId {get;set;} public string Code {get;set;}=""; public string Type {get;set;}="EXPENSE"; public string ParentCategory {get;set;}="Other"; public string CategoryName {get;set;}=""; public string Icon {get;set;}=""; public bool Active {get;set;}=true; public int SortOrder {get;set;} }
public class PersonalFcAccount { public long Id {get;set;} public long OwnerUserId {get;set;} public string Name {get;set;}=""; public string AccountType {get;set;}="BANK"; public string Institution {get;set;}=""; public string Currency {get;set;}="VND"; public decimal OpeningBalance {get;set;} public bool IncludeInNetWorth {get;set;}=true; public string Status {get;set;}="ACTIVE"; public string Notes {get;set;}=""; public DateTime CreatedAt {get;set;}=DateTime.UtcNow; public DateTime UpdatedAt {get;set;}=DateTime.UtcNow; }
public class PersonalFcTransaction { public long Id {get;set;} public long OwnerUserId {get;set;} public long? AccountId {get;set;} public long? ToAccountId {get;set;} public long? CategoryId {get;set;} public DateOnly TransactionDate {get;set;}=DateOnly.FromDateTime(DateTime.Today); public string TransactionType {get;set;}="EXPENSE"; public decimal Amount {get;set;} public string Currency {get;set;}="VND"; public string Description {get;set;}=""; public string Notes {get;set;}=""; public DateTime CreatedAt {get;set;}=DateTime.UtcNow; }
public class PersonalFcAsset { public long Id {get;set;} public long OwnerUserId {get;set;} public string AssetType {get;set;}="INVESTMENT"; public string Name {get;set;}=""; public decimal CostValue {get;set;} public decimal CurrentValue {get;set;} public string Currency {get;set;}="VND"; public bool IncludeInNetWorth {get;set;}=true; public string Notes {get;set;}=""; }
public class PersonalFcDebt { public long Id {get;set;} public long OwnerUserId {get;set;} public string Name {get;set;}=""; public string Lender {get;set;}=""; public decimal OriginalAmount {get;set;} public decimal OutstandingAmount {get;set;} public decimal InterestRate {get;set;} public string Currency {get;set;}="VND"; public string Status {get;set;}="ACTIVE"; public string Notes {get;set;}=""; }
public class PersonalFcClub { public long Id {get;set;} public long OwnerUserId {get;set;} public string Code {get;set;}=""; public string Name {get;set;}=""; public string ClubType {get;set;}="SPORT"; public string Status {get;set;}="ACTIVE"; public string Notes {get;set;}=""; public DateTime CreatedAt {get;set;}=DateTime.UtcNow; }
public class PersonalFcClubMember { public string MemberCode {get;set;}=""; public string CellPhone {get;set;}=""; public string Sex {get;set;}=""; public string SkillRank {get;set;}=""; public DateOnly? BirthDate {get;set;} public string RegistrationStatus {get;set;}="APPROVED"; public decimal MonthlyFeeAmount {get;set;} public bool RecurringFeeEnabled {get;set;} public int RecurringFeeDay {get;set;}=1; public string Notes {get;set;}=""; public bool Active {get;set;}=true; public long Id {get;set;} public long ClubId {get;set;} public long? UserId {get;set;} public string MemberName {get;set;}=""; public string Email {get;set;}=""; public string MemberRole {get;set;}="MEMBER"; public string MembershipType {get;set;}="MEMBER"; public decimal MembershipFee {get;set;} public DateOnly? JoinDate {get;set;} public string Status {get;set;}="ACTIVE"; }
public class PersonalFcClubFund {
    public string FundCode { get; set; } = "";
    public string Purpose { get; set; } = "";
    public string SourceType { get; set; } = "MEMBER_FEE";
    public long? DefaultAccountId { get; set; }
    public DateOnly? EffectiveDate { get; set; }
    public string Notes { get; set; } = "";
 public long Id {get;set;} public long ClubId {get;set;} public string Name {get;set;}=""; public string FundType {get;set;}="GENERAL"; public string Currency {get;set;}="VND"; public decimal OpeningBalance {get;set;} public string Status {get;set;}="ACTIVE"; }
public class PersonalFcClubTransaction {
    public long? PostedPersonalTransactionId { get; set; }

    public long? AccountId { get; set; }
    public DateOnly? DueDate { get; set; }
    public string SourceType { get; set; } = "MANUAL";
    public string PaymentMethod { get; set; } = "BANK_TRANSFER";
    public string ReferenceNo { get; set; } = "";
    public string Status { get; set; } = "PENDING";
    public long? ApprovedByUserId { get; set; }
    public DateTime? ApprovedAt { get; set; }
    public string PeriodKey { get; set; } = "";
    public bool AutoGenerated { get; set; }
 public long Id {get;set;} public long ClubId {get;set;} public long? FundId {get;set;} public long? MemberId {get;set;} public DateOnly TransactionDate {get;set;}=DateOnly.FromDateTime(DateTime.Today); public string TransactionType {get;set;}="INCOME"; public string Category {get;set;}=""; public decimal Amount {get;set;} public string Currency {get;set;}="VND"; public string Description {get;set;}=""; public long CreatedByUserId {get;set;} public DateTime CreatedAt {get;set;}=DateTime.UtcNow; }
public class PersonalFcClubSponsor { public long Id {get;set;} public long ClubId {get;set;} public string SponsorName {get;set;}=""; public decimal CommittedAmount {get;set;} public decimal ReceivedAmount {get;set;} public string Currency {get;set;}="VND"; public string Notes {get;set;}=""; }
public class PersonalFcClubEvent { public long Id {get;set;} public long ClubId {get;set;} public string Name {get;set;}=""; public DateOnly? EventDate {get;set;} public decimal BudgetAmount {get;set;} public decimal RegistrationIncome {get;set;} public decimal SponsorIncome {get;set;} public decimal ExpenseAmount {get;set;} public string Currency {get;set;}="VND"; public string Status {get;set;}="PLANNED"; public string Notes {get;set;}=""; }
