
import { useEffect, useMemo, useState } from 'react';
import { Edit3, Plus, Trash2, X } from 'lucide-react';
import { deleteJson, getJson, postJson, putJson } from '../lib/api';
type Criteria={id:number;code:string;name:string;weightPct:number;version:number};type Evaluation={id:number;supplier:string;project:string;periodType:string;periodStart:string;periodEnd:string;overallScore:number;rating:string;status:string};type Supplier={id:number;name:string};type Project={id:number;name:string};
const nice=(s:string)=>s.toLowerCase().replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
export function KpiPage(){
 const [canDownloadKpi,setCanDownloadKpi]=useState(false);
 useEffect(()=>{getJson<any>('/access/me').then(a=>{
   const p=a?.permissions?.KPI||[];
   setCanDownloadKpi(p.includes('DOWNLOAD'));
 }).catch(()=>setCanDownloadKpi(false))},[]);

 const [criteria,setCriteria]=useState<Criteria[]>([]),[evaluations,setEvaluations]=useState<Evaluation[]>([]),[suppliers,setSuppliers]=useState<Supplier[]>([]),[projects,setProjects]=useState<Project[]>([]),[open,setOpen]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState('');const [form,setForm]=useState({supplierId:'',projectId:'',periodType:'QUARTER',periodStart:'',periodEnd:'',evaluatorId:'1',status:'SUBMITTED'});const [scores,setScores]=useState<Record<number,string>>({});
 const load=async()=>{const [c,e,s,p]=await Promise.all([getJson<Criteria[]>('/kpi/criteria'),getJson<Evaluation[]>('/kpi/evaluations'),getJson<Supplier[]>('/suppliers'),getJson<Project[]>('/projects')]);setCriteria(c);setEvaluations(e);setSuppliers(s);setProjects(p);setScores(Object.fromEntries(c.map(x=>[x.id,'3'])))};
 useEffect(()=>{load().catch(e=>setError(String(e)))},[]);const total=useMemo(()=>criteria.reduce((a,b)=>a+b.weightPct,0),[criteria]);

 const editEvaluation=async(e:Evaluation)=>{const score=prompt('Overall score (1-5)',String(e.overallScore));if(score===null)return;const status=prompt('Status',e.status);if(status===null)return;try{await putJson(`/kpi/evaluations/${e.id}`,{overallScore:Number(score),status,rating:e.rating});await load()}catch(err){setError(String(err))}};
 const deleteEvaluation=async(e:Evaluation)=>{if(!confirm(`Delete evaluation for ${e.supplier}?`))return;try{await deleteJson(`/kpi/evaluations/${e.id}`);await load()}catch(err){setError(String(err))}};

 const submit=async(e:React.FormEvent)=>{e.preventDefault();setSaving(true);setError('');try{await postJson('/kpi/evaluations',{supplierId:Number(form.supplierId),projectId:Number(form.projectId),periodType:form.periodType,periodStart:form.periodStart,periodEnd:form.periodEnd,evaluatorId:Number(form.evaluatorId),status:form.status,scores:criteria.map(c=>({criteriaId:c.id,score:Number(scores[c.id]||0),comment:''}))});setOpen(false);await load()}catch(e){setError(String(e))}finally{setSaving(false)}};
 return <><div className="page-title"><div><h1>Supplier KPI</h1><p>Versioned, weighted performance evaluation with historical snapshots.</p></div><button className="budget-primary" onClick={()=>setOpen(true)}><Plus size={16}/> New Evaluation</button></div>{error&&<div className="budget-error">{error}</div>}
 <section className="kpi-grid"><article className="kpi-criteria-panel"><div className="kpi-panel-head"><div><h3>KPI Criteria · V{criteria[0]?.version||1}</h3><p>Weights total {total}%</p></div></div>{criteria.map(c=><div className="kpi-criteria-row" key={c.id}><div><b>{c.name}</b><span>{c.code}</span></div><strong>{c.weightPct}%</strong></div>)}</article><article className="kpi-evals-panel"><div className="kpi-panel-head"><div><h3>Recent Evaluations</h3><p>Supplier performance by project and period</p></div></div>{evaluations.length?evaluations.map(e=><div className="kpi-eval-row" key={e.id}><div className="kpi-score-ring">{e.overallScore.toFixed(2)}</div><div className="kpi-eval-main"><b>{e.supplier}</b><span>{e.project} · {e.periodType}</span><small>{e.periodStart} → {e.periodEnd}</small></div><span className={`kpi-rating ${e.rating.toLowerCase()}`}>{nice(e.rating)}</span><div className="row-actions"><button onClick={()=>editEvaluation(e)}><Edit3/></button><button className="danger" onClick={()=>deleteEvaluation(e)}><Trash2/></button></div></div>):<div className="empty-mini">No evaluations yet.</div>}</article></section>
 {open&&<div className="budget-modal-backdrop" onMouseDown={()=>setOpen(false)}><div className="budget-modal kpi-modal" onMouseDown={e=>e.stopPropagation()}><div className="budget-modal-head"><div><h3>New Supplier Evaluation</h3><p>Score each KPI from 1 to 5.</p></div><button onClick={()=>setOpen(false)}><X/></button></div><form onSubmit={submit}><div className="budget-form-grid"><label>Supplier<select required value={form.supplierId} onChange={e=>setForm({...form,supplierId:e.target.value})}><option value="">Select supplier</option>{suppliers.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Project<select required value={form.projectId} onChange={e=>setForm({...form,projectId:e.target.value})}><option value="">Select project</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Period start<input required type="date" value={form.periodStart} onChange={e=>setForm({...form,periodStart:e.target.value})}/></label><label>Period end<input required type="date" value={form.periodEnd} onChange={e=>setForm({...form,periodEnd:e.target.value})}/></label></div><div className="kpi-score-inputs">{criteria.map(c=><label key={c.id}><div><b>{c.name}</b><span>{c.weightPct}%</span></div><input type="number" min="1" max="5" step=".1" value={scores[c.id]||'3'} onChange={e=>setScores({...scores,[c.id]:e.target.value})}/></label>)}</div><div className="budget-modal-actions"><button type="button" className="secondary" onClick={()=>setOpen(false)}>Cancel</button><button className="budget-primary" disabled={saving}>{saving?'Saving...':'Save Evaluation'}</button></div></form></div></div>}
 </>;
}
