
import { useEffect, useMemo, useState } from 'react';
import { AlertOctagon, Edit3, Filter, Plus, Search, ShieldAlert, Trash2, X } from 'lucide-react';
import { deleteJson, getJson, postJson, putJson } from '../lib/api';
type Risk={id:number;projectId:number;code:string;title:string;category:string;probability:number;impact:number;severityScore:number;status:string;project:string};
type Issue={id:number;projectId:number;code:string;title:string;category:string;severity:string;status:string;targetResolutionDate?:string;project:string}; type Project={id:number;code:string;name:string};
const nice=(s:string)=>s.toLowerCase().replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
export function RisksIssuesPage(){
 const [risks,setRisks]=useState<Risk[]>([]),[issues,setIssues]=useState<Issue[]>([]),[projects,setProjects]=useState<Project[]>([]);const [tab,setTab]=useState<'risks'|'issues'>('risks'),[q,setQ]=useState(''),[status,setStatus]=useState('ALL'),[open,setOpen]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState('');
 const [risk,setRisk]=useState({projectId:'',code:'',title:'',description:'',category:'GENERAL',probability:'3',impact:'3',status:'OPEN',mitigationPlan:''});const [issue,setIssue]=useState({projectId:'',code:'',title:'',description:'',category:'GENERAL',severity:'MEDIUM',status:'OPEN',targetResolutionDate:''});
 const load=async()=>{const [r,i,p]=await Promise.all([getJson<Risk[]>('/risks'),getJson<Issue[]>('/issues'),getJson<Project[]>('/projects')]);setRisks(r);setIssues(i);setProjects(p)};useEffect(()=>{load().catch(e=>setError(String(e)))},[]);
 const rr=useMemo(()=>risks.filter(x=>(!q||`${x.code} ${x.title} ${x.project} ${x.category}`.toLowerCase().includes(q.toLowerCase()))&&(status==='ALL'||x.status===status)),[risks,q,status]);const ii=useMemo(()=>issues.filter(x=>(!q||`${x.code} ${x.title} ${x.project} ${x.category}`.toLowerCase().includes(q.toLowerCase()))&&(status==='ALL'||x.status===status)),[issues,q,status]);

 const editRisk=async(r:Risk)=>{const title=prompt('Risk title',r.title);if(title===null)return;const status=prompt('Status',r.status);if(status===null)return;const probability=prompt('Probability 1-5',String(r.probability));const impact=prompt('Impact 1-5',String(r.impact));try{await putJson(`/risks/${r.id}`,{...r,title,status,probability:Number(probability||r.probability),impact:Number(impact||r.impact)});await load()}catch(e){setError(String(e))}};
 const editIssue=async(i:Issue)=>{const title=prompt('Issue title',i.title);if(title===null)return;const status=prompt('Status',i.status);if(status===null)return;const severity=prompt('Severity',i.severity);try{await putJson(`/issues/${i.id}`,{...i,title,status,severity:severity||i.severity});await load()}catch(e){setError(String(e))}};
 const remove=async(kind:'risks'|'issues',id:number)=>{if(!confirm(`Delete this ${kind==='risks'?'risk':'issue'}?`))return;try{await deleteJson(`/${kind}/${id}`);await load()}catch(e){setError(String(e))}};

 const submit=async(e:React.FormEvent)=>{e.preventDefault();setSaving(true);setError('');try{if(tab==='risks'){const p=Number(risk.probability),i=Number(risk.impact);await postJson('/risks',{projectId:Number(risk.projectId),code:risk.code,title:risk.title,description:risk.description,category:risk.category,probability:p,impact:i,severityScore:p*i,status:risk.status,mitigationPlan:risk.mitigationPlan,responseStrategy:'MITIGATE'});}else await postJson('/issues',{projectId:Number(issue.projectId),code:issue.code,title:issue.title,description:issue.description,category:issue.category,severity:issue.severity,status:issue.status,targetResolutionDate:issue.targetResolutionDate||null,reportedDate:new Date().toISOString().slice(0,10)});setOpen(false);await load()}catch(e){setError(String(e))}finally{setSaving(false)}};
 return <><div className="page-title"><div><h1>Risks & Issues</h1><p>{risks.length} risks and {issues.length} issues in the current workspace.</p></div><button className="budget-primary" onClick={()=>setOpen(true)}><Plus size={16}/> Add {tab==='risks'?'Risk':'Issue'}</button></div>{error&&<div className="budget-error">{error}</div>}
 <div className="module-tabs"><button className={tab==='risks'?'active':''} onClick={()=>{setTab('risks');setStatus('ALL')}}><ShieldAlert size={15}/> Risks</button><button className={tab==='issues'?'active':''} onClick={()=>{setTab('issues');setStatus('ALL')}}><AlertOctagon size={15}/> Issues</button></div>
 <section className="data-module-panel"><div className="data-module-toolbar"><label className="module-search"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder={`Search ${tab}...`}/></label><label className="module-filter"><Filter/><select value={status} onChange={e=>setStatus(e.target.value)}><option value="ALL">All status</option>{(tab==='risks'?['OPEN','MONITORING','MITIGATING','CLOSED']:['OPEN','INVESTIGATING','ACTION_REQUIRED','RESOLVED','CLOSED']).map(s=><option key={s}>{s}</option>)}</select></label></div>
 {tab==='risks'?<div className="module-table-wrap"><table className="module-table"><thead><tr><th>Code</th><th>Risk</th><th>Project</th><th>Category</th><th>P × I</th><th>Score</th><th>Status</th><th>Actions</th></tr></thead><tbody>{rr.map(r=><tr key={r.id}><td>{r.code}</td><td><b>{r.title}</b></td><td>{r.project}</td><td>{r.category}</td><td>{r.probability} × {r.impact}</td><td><strong className={r.severityScore>=17?'score-bad':r.severityScore>=10?'score-mid':'score-good'}>{r.severityScore}</strong></td><td><span className={`module-pill ${r.status.toLowerCase()}`}>{nice(r.status)}</span></td><td><div className="row-actions"><button onClick={()=>editRisk(r)}><Edit3/></button><button className="danger" onClick={()=>remove('risks',r.id)}><Trash2/></button></div></td></tr>)}</tbody></table></div>:<div className="module-table-wrap"><table className="module-table"><thead><tr><th>Code</th><th>Issue</th><th>Project</th><th>Category</th><th>Severity</th><th>Target</th><th>Status</th></tr></thead><tbody>{ii.map(i=><tr key={i.id}><td>{i.code}</td><td><b>{i.title}</b></td><td>{i.project}</td><td>{i.category}</td><td><span className={`severity ${i.severity.toLowerCase()}`}>{nice(i.severity)}</span></td><td>{i.targetResolutionDate||'—'}</td><td><span className={`module-pill ${i.status.toLowerCase()}`}>{nice(i.status)}</span></td><td><div className="row-actions"><button onClick={()=>editIssue(i)}><Edit3/></button><button className="danger" onClick={()=>remove('issues',i.id)}><Trash2/></button></div></td></tr>)}</tbody></table></div>}</section>
 {open&&<div className="budget-modal-backdrop" onMouseDown={()=>setOpen(false)}><div className="budget-modal" onMouseDown={e=>e.stopPropagation()}><div className="budget-modal-head"><div><h3>Add {tab==='risks'?'Risk':'Issue'}</h3><p>Register project exposure or an active issue.</p></div><button onClick={()=>setOpen(false)}><X/></button></div><form onSubmit={submit}>{tab==='risks'?<>
 <label>Project<select required value={risk.projectId} onChange={e=>setRisk({...risk,projectId:e.target.value})}><option value="">Select project</option>{projects.map(p=><option key={p.id} value={p.id}>{p.code} — {p.name}</option>)}</select></label><div className="budget-form-grid"><label>Code<input required value={risk.code} onChange={e=>setRisk({...risk,code:e.target.value})}/></label><label>Category<input value={risk.category} onChange={e=>setRisk({...risk,category:e.target.value})}/></label><label>Probability<input type="number" min="1" max="5" value={risk.probability} onChange={e=>setRisk({...risk,probability:e.target.value})}/></label><label>Impact<input type="number" min="1" max="5" value={risk.impact} onChange={e=>setRisk({...risk,impact:e.target.value})}/></label></div><label>Title<input required value={risk.title} onChange={e=>setRisk({...risk,title:e.target.value})}/></label><label>Mitigation plan<textarea rows={3} value={risk.mitigationPlan} onChange={e=>setRisk({...risk,mitigationPlan:e.target.value})}/></label>
 </>:<><label>Project<select required value={issue.projectId} onChange={e=>setIssue({...issue,projectId:e.target.value})}><option value="">Select project</option>{projects.map(p=><option key={p.id} value={p.id}>{p.code} — {p.name}</option>)}</select></label><div className="budget-form-grid"><label>Code<input required value={issue.code} onChange={e=>setIssue({...issue,code:e.target.value})}/></label><label>Severity<select value={issue.severity} onChange={e=>setIssue({...issue,severity:e.target.value})}><option>LOW</option><option>MEDIUM</option><option>HIGH</option><option>CRITICAL</option></select></label></div><label>Title<input required value={issue.title} onChange={e=>setIssue({...issue,title:e.target.value})}/></label><label>Description<textarea rows={3} value={issue.description} onChange={e=>setIssue({...issue,description:e.target.value})}/></label></>}<div className="budget-modal-actions"><button type="button" className="secondary" onClick={()=>setOpen(false)}>Cancel</button><button className="budget-primary" disabled={saving}>{saving?'Saving...':'Save'}</button></div></form></div></div>}
 </>;
}
