import { useEffect, useMemo, useState } from 'react';
import { Edit3, KeyRound, Plus, Search, Trash2, UsersRound, X } from 'lucide-react';
import { deleteJson, getJson, postJson, putJson } from '../lib/api';

type User={id:number;orgUnitId:number;name:string;email:string;jobTitle:string;department:string;role:string;status:string};
type Project={id:number;code:string;name:string};
type Member={id:number;projectId:number;project:string;userId:number;user:string;projectRole:string;allocationPct:number;startDate?:string;endDate?:string;isActive:boolean};

const blankUser={orgUnitId:1,name:'',email:'',jobTitle:'',department:'IT',role:'MEMBER',status:'ACTIVE'};
const blankMember={projectId:'',userId:'',projectRole:'MEMBER',allocationPct:'100',startDate:'',endDate:'',isActive:true};

export function TeamManagementPage(){
 const [users,setUsers]=useState<User[]>([]);const [projects,setProjects]=useState<Project[]>([]);const [members,setMembers]=useState<Member[]>([]);
 const [q,setQ]=useState('');const [projectId,setProjectId]=useState('ALL');const [userForm,setUserForm]=useState<any>(null);const [editingUser,setEditingUser]=useState<User|null>(null);const [memberForm,setMemberForm]=useState<any>(null);const [editingMember,setEditingMember]=useState<Member|null>(null);const [error,setError]=useState('');
 const load=async()=>{const [u,p,m]=await Promise.all([getJson<User[]>('/team/users'),getJson<Project[]>('/projects'),getJson<Member[]>('/project-members')]);setUsers(u);setProjects(p);setMembers(m)};
 useEffect(()=>{load().catch(e=>setError(String(e)))},[]);
 const filteredUsers=useMemo(()=>users.filter(u=>!q||`${u.name} ${u.email} ${u.jobTitle} ${u.department}`.toLowerCase().includes(q.toLowerCase())),[users,q]);
 const filteredMembers=useMemo(()=>members.filter(m=>projectId==='ALL'||String(m.projectId)===projectId),[members,projectId]);
 const saveUser=async(e:React.FormEvent)=>{e.preventDefault();try{editingUser?await putJson(`/team/users/${editingUser.id}`,userForm):await postJson('/team/users',userForm);setUserForm(null);setEditingUser(null);await load()}catch(e){setError(String(e))}};
 const removeUser=async(u:User)=>{if(!confirm(`Remove ${u.name}? Referenced users will be deactivated instead.`))return;try{await deleteJson(`/team/users/${u.id}`);await load()}catch(e){setError(String(e))}};
 const resetLogin=async(u:User)=>{if(!confirm(`Create/reset login for ${u.name}?`))return;try{const r=await postJson<{temporaryPassword:string;email:string}>(`/team/users/${u.id}/reset-login`,{});alert(`Login ready for ${u.name}\nEmail: ${r.email}\nTemporary password: ${r.temporaryPassword}\nThe user must change it after first sign-in.`)}catch(e){setError(String(e))}};

 const saveMember=async(e:React.FormEvent)=>{e.preventDefault();const payload={...memberForm,projectId:Number(memberForm.projectId),userId:Number(memberForm.userId),allocationPct:Number(memberForm.allocationPct||0),startDate:memberForm.startDate||null,endDate:memberForm.endDate||null};try{editingMember?await putJson(`/project-members/${editingMember.id}`,payload):await postJson('/project-members',payload);setMemberForm(null);setEditingMember(null);await load()}catch(e){setError(String(e))}};
 const removeMember=async(m:Member)=>{if(!confirm(`Remove ${m.user} from ${m.project}?`))return;try{await deleteJson(`/project-members/${m.id}`);await load()}catch(e){setError(String(e))}};
 return <>
  <div className="page-title"><div><h1>Project Team</h1><p>Maintain the full project team roster and allocate people across multiple projects.</p></div><div className="project-actions"><button className="secondary" onClick={()=>{setEditingUser(null);setUserForm({...blankUser})}}><Plus size={16}/> Add Person</button><button className="budget-primary" onClick={()=>{setEditingMember(null);setMemberForm({...blankMember})}}><UsersRound size={16}/> Assign to Project</button></div></div>
  {error&&<div className="budget-error">{error}</div>}
  <section className="performance-kpis"><div><span>People</span><b>{users.length}</b></div><div><span>Active People</span><b>{users.filter(x=>x.status==='ACTIVE').length}</b></div><div><span>Project Assignments</span><b>{members.length}</b></div><div><span>Projects with Team</span><b>{new Set(members.map(x=>x.projectId)).size}</b></div></section>
  <section className="data-module-panel"><div className="data-module-toolbar"><label className="module-search"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search team members..."/></label></div><div className="module-table-wrap"><table className="module-table"><thead><tr><th>Name</th><th>Job Title</th><th>Department</th><th>Email</th><th>Role</th><th>Status</th><th>Actions</th></tr></thead><tbody>{filteredUsers.map(u=><tr key={u.id}><td><b>{u.name}</b></td><td>{u.jobTitle||'—'}</td><td>{u.department||'—'}</td><td>{u.email}</td><td>{u.role}</td><td><span className={`module-pill ${u.status.toLowerCase()}`}>{u.status}</span></td><td><div className="row-actions"><button title="Create / reset login" onClick={()=>resetLogin(u)}><KeyRound/></button><button onClick={()=>{setEditingUser(u);setUserForm({...u})}}><Edit3/></button><button className="danger" onClick={()=>removeUser(u)}><Trash2/></button></div></td></tr>)}</tbody></table></div></section>
  <section className="data-module-panel"><div className="data-module-toolbar"><b>Project Assignments</b><select value={projectId} onChange={e=>setProjectId(e.target.value)}><option value="ALL">All projects</option>{projects.map(p=><option key={p.id} value={p.id}>{p.code} — {p.name}</option>)}</select></div><div className="module-table-wrap"><table className="module-table"><thead><tr><th>Project</th><th>Person</th><th>Project Role</th><th>Allocation</th><th>Start</th><th>End</th><th>Status</th><th>Actions</th></tr></thead><tbody>{filteredMembers.map(m=><tr key={m.id}><td><b>{m.project}</b></td><td>{m.user}</td><td>{m.projectRole}</td><td>{m.allocationPct}%</td><td>{m.startDate||'—'}</td><td>{m.endDate||'—'}</td><td>{m.isActive?'ACTIVE':'INACTIVE'}</td><td><div className="row-actions"><button onClick={()=>{setEditingMember(m);setMemberForm({...m,projectId:String(m.projectId),userId:String(m.userId),allocationPct:String(m.allocationPct),startDate:m.startDate||'',endDate:m.endDate||''})}}><Edit3/></button><button className="danger" onClick={()=>removeMember(m)}><Trash2/></button></div></td></tr>)}</tbody></table></div></section>
  {userForm&&<div className="budget-modal-backdrop" onMouseDown={()=>setUserForm(null)}><div className="budget-modal" onMouseDown={e=>e.stopPropagation()}><div className="budget-modal-head"><div><h3>{editingUser?'Edit':'Add'} Person</h3><p>Add anyone participating in the project team, not only people from the imported UPF file.</p></div><button onClick={()=>setUserForm(null)}><X/></button></div><form onSubmit={saveUser}><div className="budget-form-grid"><label>Name<input required value={userForm.name} onChange={e=>setUserForm({...userForm,name:e.target.value})}/></label><label>Email<input required type="email" value={userForm.email} onChange={e=>setUserForm({...userForm,email:e.target.value})}/></label><label>Job title<input value={userForm.jobTitle} onChange={e=>setUserForm({...userForm,jobTitle:e.target.value})}/></label><label>Department<input value={userForm.department} onChange={e=>setUserForm({...userForm,department:e.target.value})}/></label><label>System role<select value={userForm.role} onChange={e=>setUserForm({...userForm,role:e.target.value})}><option>MEMBER</option><option>PROJECT_MANAGER</option><option>HOD</option><option>SPONSOR</option><option>ADMIN</option></select></label><label>Status<select value={userForm.status} onChange={e=>setUserForm({...userForm,status:e.target.value})}><option>ACTIVE</option><option>INACTIVE</option></select></label></div><div className="budget-modal-actions"><button type="button" className="secondary" onClick={()=>setUserForm(null)}>Cancel</button><button className="budget-primary">Save</button></div></form></div></div>}
  {memberForm&&<div className="budget-modal-backdrop" onMouseDown={()=>setMemberForm(null)}><div className="budget-modal" onMouseDown={e=>e.stopPropagation()}><div className="budget-modal-head"><div><h3>{editingMember?'Edit':'Assign'} Project Member</h3><p>One person can be allocated to multiple projects with different roles and percentages.</p></div><button onClick={()=>setMemberForm(null)}><X/></button></div><form onSubmit={saveMember}><label>Project<select required disabled={!!editingMember} value={memberForm.projectId} onChange={e=>setMemberForm({...memberForm,projectId:e.target.value})}><option value="">Select project</option>{projects.map(p=><option key={p.id} value={p.id}>{p.code} — {p.name}</option>)}</select></label><label>Person<select required disabled={!!editingMember} value={memberForm.userId} onChange={e=>setMemberForm({...memberForm,userId:e.target.value})}><option value="">Select person</option>{users.filter(u=>u.status==='ACTIVE').map(u=><option key={u.id} value={u.id}>{u.name} — {u.jobTitle||u.department}</option>)}</select></label><div className="budget-form-grid"><label>Project role<input value={memberForm.projectRole} onChange={e=>setMemberForm({...memberForm,projectRole:e.target.value})}/></label><label>Allocation %<input type="number" min="0" max="100" value={memberForm.allocationPct} onChange={e=>setMemberForm({...memberForm,allocationPct:e.target.value})}/></label><label>Start<input type="date" value={memberForm.startDate} onChange={e=>setMemberForm({...memberForm,startDate:e.target.value})}/></label><label>End<input type="date" value={memberForm.endDate} onChange={e=>setMemberForm({...memberForm,endDate:e.target.value})}/></label></div><div className="budget-modal-actions"><button type="button" className="secondary" onClick={()=>setMemberForm(null)}>Cancel</button><button className="budget-primary">Save Assignment</button></div></form></div></div>}
 </>;
}
