import { useEffect, useMemo, useRef, useState } from 'react';
import { Download, Edit3, Link2, Plus, Search, Trash2, Upload, X } from 'lucide-react';
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { deleteJson, getJson, postJson, putJson } from '../lib/api';
import { BusinessUnitSelect, CategorySelect } from '../components/MasterDataSelect';

type Project={id:number;code:string;name:string};
type Item={id:number;budgetYear:number;orgUnit:string;sourceSheet:string;sourceRow:number;projectId?:number;project?:string;name:string;category:string;vendor:string;plannedAmount:number;quantity?:number;unitPrice?:number;plannedMonth:string;monthlyPlanJson:string;note:string;status:string createdBy?: string | null; editedBy?: string | null; createdAt?: string | null; updatedAt?: string | null; createdByUserId?: number | null; updatedByUserId?: number | null;};
type Overview={year:number;totalPlanned:number;itemCount:number;linkedProjects:number;unlinkedItems:number;orgUnits:string[];byUnit:{orgUnit:string;amount:number;items:number}[];items:Item[]};
const money=(n:number)=>n>=1e9?`${(n/1e9).toFixed(2)}B ₫`:n>=1e6?`${(n/1e6).toFixed(1)}M ₫`:`${new Intl.NumberFormat('en-US').format(n)} ₫`;
const blank={budgetYear:new Date().getFullYear(),orgUnit:'',sourceSheet:'MANUAL',sourceRow:0,projectId:'',name:'',category:'',vendor:'',plannedAmount:'0',quantity:'',unitPrice:'',plannedMonth:'',note:'',status:'PLANNED'};

export function BudgetPlanningPage(){
 const [budgetMasterOptions,setBudgetMasterOptions]=useState<any>({orgUnits:[]});
 const budgetImportRef=useRef<HTMLInputElement|null>(null);
 const [data,setData]=useState<Overview|null>(null); const [projects,setProjects]=useState<Project[]>([]); const [years,setYears]=useState<number[]>([]); const [year,setYear]=useState(new Date().getFullYear()); const [unit,setUnit]=useState('ALL'); const [q,setQ]=useState(''); const [editing,setEditing]=useState<Item|null>(null); const [form,setForm]=useState<any>(blank); const [error,setError]=useState('');
 const load=async()=>{const [d,p,y]=await Promise.all([getJson<Overview>(`/budget-plan/overview?year=${year}&orgUnit=${encodeURIComponent(unit)}`),getJson<Project[]>('/projects'),getJson<number[]>('/budget-plan/years')]);setData(d);setProjects(p);setYears(y)};
 useEffect(()=>{getJson<any>('/settings/options').then(setBudgetMasterOptions).catch(()=>{})},[]);
 useEffect(()=>{load().catch(e=>setError(String(e)))},[unit,year]);
 const rows=useMemo(()=>data?.items.filter(x=>!q||`${x.name} ${x.orgUnit} ${x.category} ${x.vendor} ${x.project||''}`.toLowerCase().includes(q.toLowerCase()))||[],[data,q]);
 const openNew=()=>{setEditing(null);setForm({...blank,budgetYear:year,orgUnit:unit==='ALL'?'':unit})};
 const openEdit=(x:Item)=>{setEditing(x);setForm({...x,projectId:x.projectId?String(x.projectId):'',plannedAmount:String(x.plannedAmount),quantity:x.quantity??'',unitPrice:x.unitPrice??''})};
 const save=async(e:React.FormEvent)=>{e.preventDefault();const payload={...form,budgetYear:Number(form.budgetYear),projectId:form.projectId?Number(form.projectId):null,plannedAmount:Number(form.plannedAmount||0),quantity:form.quantity===''?null:Number(form.quantity),unitPrice:form.unitPrice===''?null:Number(form.unitPrice)};try{editing?await putJson(`/budget-plan/${editing.id}`,payload):await postJson('/budget-plan',payload);setEditing(null);setForm(null);await load()}catch(e){setError(String(e))}};
 const del=async(x:Item)=>{if(!confirm(`Delete budget plan item “${x.name}”?`))return;try{await deleteJson(`/budget-plan/${x.id}`);await load()}catch(e){setError(String(e))}};
 const cloneYear=async()=>{const target=Number(prompt('Create budget plan for year:',String(year+1)));if(!target||target===year)return;try{await postJson(`/budget-plan/years/${year}/clone?targetYear=${target}`);setYear(target);setUnit('ALL')}catch(e){setError(String(e))}};
 const exportBudgetExcel=async()=>{setError('');try{const r=await fetch(`/api/excel/budget/export/${year}`,{credentials:'same-origin'});if(!r.ok)throw new Error(await r.text());const blob=await r.blob();const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`MPMS_Budget_Plan_${year}.xlsx`;a.click();URL.revokeObjectURL(url)}catch(e){setError(String(e))}};
 const importBudgetExcel=async(e:React.ChangeEvent<HTMLInputElement>)=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;setError('');try{const f1=new FormData();f1.append('file',file);let r=await fetch('/api/excel/budget/import?dryRun=true&mode=merge',{method:'POST',body:f1,credentials:'same-origin'});if(!r.ok)throw new Error(await r.text());const preview=await r.json();const warnings=(preview.warnings||[]).join('\n');if(!confirm(`Budget Excel preview\n\nFormat: ${preview.format||'unknown'}\nItems: ${preview.itemCount||0}\nYears: ${(preview.years||[]).join(', ')}\nTotal planned: ${money(preview.totalPlanned||0)}${warnings?`\n\nWarnings:\n${warnings}`:''}\n\nMerge into MPMS? Existing rows matched by Year + Business Unit + Plan Item will be updated.`))return;const f2=new FormData();f2.append('file',file);r=await fetch('/api/excel/budget/import?dryRun=false&mode=merge',{method:'POST',body:f2,credentials:'same-origin'});if(!r.ok)throw new Error(await r.text());const result=await r.json();alert(`Budget import completed. Inserted: ${result.inserted||0}; Updated: ${result.updated||0}.${result.warnings?.length?`\nWarnings: ${result.warnings.join('; ')}`:''}`);await load()}catch(e){setError(String(e))}};

 if(!data)return <div className="loading">{error||'Loading annual budget plan...'}</div>;
 return <>
  <div className="page-title"><div><h1>Annual Budget Plan</h1><p>Annual planning by business unit and project. The 2026 workbook is the first imported baseline; future years use the same structure.</p></div><div className="project-actions"><input ref={budgetImportRef} hidden type="file" accept=".xlsx" onChange={importBudgetExcel}/><button className="secondary" onClick={()=>budgetImportRef.current?.click()}><Upload size={16}/> Import Excel</button><button className="secondary" onClick={exportBudgetExcel}><Download size={16}/> Export Excel</button><select className="year-select" value={year} onChange={e=>{setYear(Number(e.target.value));setUnit('ALL')}}>{Array.from(new Set([year,...years])).sort((a,b)=>b-a).map(y=><option key={y} value={y}>{y}</option>)}</select><button className="secondary" onClick={cloneYear}>Create {year+1} from {year}</button><button className="budget-primary" onClick={openNew}><Plus size={16}/> New Plan Item</button></div></div>
  {error&&<div className="budget-error">{error}</div>}
  <section className="plan-kpis"><div><span>Total Planned</span><b>{money(data.totalPlanned)}</b></div><div><span>Plan Items</span><b>{data.itemCount}</b></div><div><span>Linked to Projects</span><b>{data.linkedProjects}</b></div><div><span>Need Project Mapping</span><b>{data.unlinkedItems}</b></div></section>
  <section className="plan-grid"><article className="project-panel"><h3>Budget by Business Unit</h3><div className="plan-chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={data.byUnit}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="orgUnit" interval={0} angle={-18} textAnchor="end" height={70}/><YAxis tickFormatter={v=>`${(Number(v)/1e9).toFixed(0)}B`}/><Tooltip formatter={(v:any)=>money(Number(v))}/><Bar dataKey="amount" fill="#082d57" radius={[4,4,0,0]}/></BarChart></ResponsiveContainer></div></article><article className="project-panel"><h3>Source Coverage</h3><div className="source-coverage">{data.byUnit.map(x=><div key={x.orgUnit}><span>{x.orgUnit}</span><b>{x.items} items</b><em>{money(x.amount)}</em></div>)}</div></article></section>
  <section className="data-module-panel"><div className="data-module-toolbar"><label className="module-search"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search budget plan..."/></label><select value={unit} onChange={e=>setUnit(e.target.value)}><option value="ALL">All business units</option>{budgetMasterOptions.orgUnits?.filter((x:any)=>x.status==="ACTIVE").map((x:any)=><option key={x.id} value={x.code}>{x.code} — {x.name}</option>)}</select></div><div className="module-table-wrap"><table className="module-table budget-plan-table"><thead><tr><th>Business Unit</th><th>Plan Item</th><th>Category</th><th>Vendor</th><th>Planned</th><th>Project</th><th>Source</th><th>Created by</th><th>Edited by</th><th>Actions</th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td>{x.orgUnit}</td><td><b>{x.name}</b><small>{x.plannedMonth||x.note}</small></td><td>{x.category||'—'}</td><td>{x.vendor||'—'}</td><td><b>{money(x.plannedAmount)}</b></td><td>{x.project?<span className="linked-project"><Link2/> {x.project}</span>:<span className="unlinked">Unlinked</span>}</td><td>{x.sourceSheet} · row {x.sourceRow}</td><td><b>{x.createdBy||'Legacy / System'}</b><small>{x.createdAt?new Date(x.createdAt).toLocaleString():'—'}</small></td><td><b>{x.editedBy||x.createdBy||'—'}</b><small>{x.updatedAt?new Date(x.updatedAt).toLocaleString():'—'}</small></td><td><div className="row-actions"><button onClick={()=>openEdit(x)}><Edit3/></button><button className="danger" onClick={()=>del(x)}><Trash2/></button></div></td></tr>)}</tbody></table></div></section>
  {(form!==null)&&(editing!==null||form!==blank)&&<div className="budget-modal-backdrop" onMouseDown={()=>setForm(null)}><div className="budget-modal" onMouseDown={e=>e.stopPropagation()}><div className="budget-modal-head"><div><h3>{editing?'Edit':'New'} Budget Plan Item</h3><p>Map annual budget planning to projects and keep source traceability.</p></div><button onClick={()=>setForm(null)}><X/></button></div><form onSubmit={save}><div className="budget-form-grid"><label>Budget year<input required type="number" min="2020" max="2100" value={form.budgetYear} onChange={e=>setForm({...form,budgetYear:e.target.value})}/></label><label>Business Unit<BusinessUnitSelect value={form.orgUnit||''} onChange={value=>setForm({...form,orgUnit:value})}/></label><label>Project<select value={form.projectId||''} onChange={e=>setForm({...form,projectId:e.target.value})}><option value="">Unlinked</option>{projects.map(p=><option key={p.id} value={p.id}>{p.code} — {p.name}</option>)}</select></label><label>Plan item<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Category<CategorySelect scope="BUDGET" required value={form.category||''} onChange={value=>setForm({...form,category:value})}/></label><label>Vendor<input value={form.vendor||''} onChange={e=>setForm({...form,vendor:e.target.value})}/></label><label>Planned amount<input type="number" min="0" value={form.plannedAmount} onChange={e=>setForm({...form,plannedAmount:e.target.value})}/></label><label>Quantity<input type="number" step="any" value={form.quantity??''} onChange={e=>setForm({...form,quantity:e.target.value})}/></label><label>Unit price<input type="number" min="0" value={form.unitPrice??''} onChange={e=>setForm({...form,unitPrice:e.target.value})}/></label></div><label>Note<textarea rows={3} value={form.note||''} onChange={e=>setForm({...form,note:e.target.value})}/></label><div className="budget-modal-actions"><button type="button" className="secondary" onClick={()=>setForm(null)}>Cancel</button><button className="budget-primary">Save</button></div></form></div></div>}
 </>;
}
