using Microsoft.EntityFrameworkCore;
using System.Data.Common;

namespace MAIPT.PM.Api.Data;

public static class ClubFinanceSchema
{
    public static async Task EnsureAsync(AppDbContext db)
    {
        if (db.Database.IsSqlServer())
        {
            await db.Database.ExecuteSqlRawAsync("""
IF OBJECT_ID(N'dbo.PersonalFcClubFunds',N'U') IS NOT NULL
BEGIN
 IF COL_LENGTH(N'dbo.PersonalFcClubFunds','FundCode') IS NULL ALTER TABLE dbo.PersonalFcClubFunds ADD FundCode NVARCHAR(50) NOT NULL DEFAULT N'';
 IF COL_LENGTH(N'dbo.PersonalFcClubFunds','Purpose') IS NULL ALTER TABLE dbo.PersonalFcClubFunds ADD Purpose NVARCHAR(1000) NOT NULL DEFAULT N'';
 IF COL_LENGTH(N'dbo.PersonalFcClubFunds','SourceType') IS NULL ALTER TABLE dbo.PersonalFcClubFunds ADD SourceType NVARCHAR(50) NOT NULL DEFAULT N'MEMBER_FEE';
 IF COL_LENGTH(N'dbo.PersonalFcClubFunds','DefaultAccountId') IS NULL ALTER TABLE dbo.PersonalFcClubFunds ADD DefaultAccountId BIGINT NULL;
 IF COL_LENGTH(N'dbo.PersonalFcClubFunds','EffectiveDate') IS NULL ALTER TABLE dbo.PersonalFcClubFunds ADD EffectiveDate DATE NULL;
 IF COL_LENGTH(N'dbo.PersonalFcClubFunds','Notes') IS NULL ALTER TABLE dbo.PersonalFcClubFunds ADD Notes NVARCHAR(MAX) NOT NULL DEFAULT N'';
END;

IF OBJECT_ID(N'dbo.PersonalFcClubTransactions',N'U') IS NOT NULL
BEGIN
 IF COL_LENGTH(N'dbo.PersonalFcClubTransactions','FundId') IS NULL ALTER TABLE dbo.PersonalFcClubTransactions ADD FundId BIGINT NULL;
 IF COL_LENGTH(N'dbo.PersonalFcClubTransactions','AccountId') IS NULL ALTER TABLE dbo.PersonalFcClubTransactions ADD AccountId BIGINT NULL;
 IF COL_LENGTH(N'dbo.PersonalFcClubTransactions','MemberId') IS NULL ALTER TABLE dbo.PersonalFcClubTransactions ADD MemberId BIGINT NULL;
 IF COL_LENGTH(N'dbo.PersonalFcClubTransactions','DueDate') IS NULL ALTER TABLE dbo.PersonalFcClubTransactions ADD DueDate DATE NULL;
 IF COL_LENGTH(N'dbo.PersonalFcClubTransactions','SourceType') IS NULL ALTER TABLE dbo.PersonalFcClubTransactions ADD SourceType NVARCHAR(50) NOT NULL DEFAULT N'MANUAL';
 IF COL_LENGTH(N'dbo.PersonalFcClubTransactions','Category') IS NULL ALTER TABLE dbo.PersonalFcClubTransactions ADD Category NVARCHAR(100) NOT NULL DEFAULT N'OTHER';
 IF COL_LENGTH(N'dbo.PersonalFcClubTransactions','PaymentMethod') IS NULL ALTER TABLE dbo.PersonalFcClubTransactions ADD PaymentMethod NVARCHAR(50) NOT NULL DEFAULT N'BANK_TRANSFER';
 IF COL_LENGTH(N'dbo.PersonalFcClubTransactions','ReferenceNo') IS NULL ALTER TABLE dbo.PersonalFcClubTransactions ADD ReferenceNo NVARCHAR(200) NOT NULL DEFAULT N'';
 IF COL_LENGTH(N'dbo.PersonalFcClubTransactions','Description') IS NULL ALTER TABLE dbo.PersonalFcClubTransactions ADD Description NVARCHAR(1000) NOT NULL DEFAULT N'';
 IF COL_LENGTH(N'dbo.PersonalFcClubTransactions','Status') IS NULL ALTER TABLE dbo.PersonalFcClubTransactions ADD Status NVARCHAR(30) NOT NULL DEFAULT N'PENDING';
 IF COL_LENGTH(N'dbo.PersonalFcClubTransactions','ApprovedByUserId') IS NULL ALTER TABLE dbo.PersonalFcClubTransactions ADD ApprovedByUserId BIGINT NULL;
 IF COL_LENGTH(N'dbo.PersonalFcClubTransactions','ApprovedAt') IS NULL ALTER TABLE dbo.PersonalFcClubTransactions ADD ApprovedAt DATETIME2 NULL;
 IF COL_LENGTH(N'dbo.PersonalFcClubTransactions','PeriodKey') IS NULL ALTER TABLE dbo.PersonalFcClubTransactions ADD PeriodKey NVARCHAR(7) NOT NULL DEFAULT N'';
 IF COL_LENGTH(N'dbo.PersonalFcClubTransactions','AutoGenerated') IS NULL ALTER TABLE dbo.PersonalFcClubTransactions ADD AutoGenerated BIT NOT NULL DEFAULT 0;
 IF COL_LENGTH(N'dbo.PersonalFcClubTransactions','PostedPersonalTransactionId') IS NULL ALTER TABLE dbo.PersonalFcClubTransactions ADD PostedPersonalTransactionId BIGINT NULL;
END;
""");
        }
        else
        {
            await AddSqliteColumnAsync(db, "PersonalFcClubFunds", "FundCode", "TEXT NOT NULL DEFAULT ''");
            await AddSqliteColumnAsync(db, "PersonalFcClubFunds", "Purpose", "TEXT NOT NULL DEFAULT ''");
            await AddSqliteColumnAsync(db, "PersonalFcClubFunds", "SourceType", "TEXT NOT NULL DEFAULT 'MEMBER_FEE'");
            await AddSqliteColumnAsync(db, "PersonalFcClubFunds", "DefaultAccountId", "INTEGER NULL");
            await AddSqliteColumnAsync(db, "PersonalFcClubFunds", "EffectiveDate", "TEXT NULL");
            await AddSqliteColumnAsync(db, "PersonalFcClubFunds", "Notes", "TEXT NOT NULL DEFAULT ''");

            await AddSqliteColumnAsync(db, "PersonalFcClubTransactions", "FundId", "INTEGER NULL");
            await AddSqliteColumnAsync(db, "PersonalFcClubTransactions", "AccountId", "INTEGER NULL");
            await AddSqliteColumnAsync(db, "PersonalFcClubTransactions", "MemberId", "INTEGER NULL");
            await AddSqliteColumnAsync(db, "PersonalFcClubTransactions", "DueDate", "TEXT NULL");
            await AddSqliteColumnAsync(db, "PersonalFcClubTransactions", "SourceType", "TEXT NOT NULL DEFAULT 'MANUAL'");
            await AddSqliteColumnAsync(db, "PersonalFcClubTransactions", "Category", "TEXT NOT NULL DEFAULT 'OTHER'");
            await AddSqliteColumnAsync(db, "PersonalFcClubTransactions", "PaymentMethod", "TEXT NOT NULL DEFAULT 'BANK_TRANSFER'");
            await AddSqliteColumnAsync(db, "PersonalFcClubTransactions", "ReferenceNo", "TEXT NOT NULL DEFAULT ''");
            await AddSqliteColumnAsync(db, "PersonalFcClubTransactions", "Description", "TEXT NOT NULL DEFAULT ''");
            await AddSqliteColumnAsync(db, "PersonalFcClubTransactions", "Status", "TEXT NOT NULL DEFAULT 'PENDING'");
            await AddSqliteColumnAsync(db, "PersonalFcClubTransactions", "ApprovedByUserId", "INTEGER NULL");
            await AddSqliteColumnAsync(db, "PersonalFcClubTransactions", "ApprovedAt", "TEXT NULL");
            await AddSqliteColumnAsync(db, "PersonalFcClubTransactions", "PeriodKey", "TEXT NOT NULL DEFAULT ''");
            await AddSqliteColumnAsync(db, "PersonalFcClubTransactions", "AutoGenerated", "INTEGER NOT NULL DEFAULT 0");
            await AddSqliteColumnAsync(db, "PersonalFcClubTransactions", "PostedPersonalTransactionId", "INTEGER NULL");
        }
    }

    static async Task AddSqliteColumnAsync(AppDbContext db,string table,string column,string definition)
    {
        var conn=db.Database.GetDbConnection();
        if(conn.State!=System.Data.ConnectionState.Open) await conn.OpenAsync();
        await using var check=conn.CreateCommand();
        check.CommandText=$"PRAGMA table_info({table})";
        await using var r=await check.ExecuteReaderAsync();
        var exists=false;
        while(await r.ReadAsync())
            if(string.Equals(Convert.ToString(r["name"]),column,StringComparison.OrdinalIgnoreCase)){exists=true;break;}
        await r.DisposeAsync();
        if(exists)return;
        await using var cmd=conn.CreateCommand();
        cmd.CommandText=$"ALTER TABLE {table} ADD COLUMN {column} {definition}";
        await cmd.ExecuteNonQueryAsync();
    }
}
